POST   http://localhost:5000/api/skill
Content-Type: application/json

{
    "name": "C##"
}
###
DELETE http://localhost:5000/api/skill
Content-Type: application/json

{
  "id": 1
}

###
GET http://localhost:5000/api/skill
Content-Type: application/json

###
PUT  http://localhost:5000/api/skill
Content-Type: application/json

{
  "id": 1,
  "newData": {
    "name": "Rust"
  }
}