POST   http://localhost:5000/api/wilder
Content-Type: application/json

{
    "name": "Bobby Doe"
}
###
DELETE http://localhost:5000/api/wilder
Content-Type: application/json

{
  "id": 9
}

###
GET http://localhost:5000/api/wilder
Content-Type: application/json

###
PUT  http://localhost:5000/api/wilder
Content-Type: application/json

{
  "id": 1,
  "newData": {
    "name": "John"
  }
}

###
PUT http://localhost:5000/api/addSkill
Content-Type: application/json

{
    "wilderName": "Jean",
    "skillName": "Javascript"
}